apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: portal-db
  namespace: acm-portal
spec:
  instances: 2
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: portal
      owner: portal
  enablePDB: false
  resources:
    requests: { cpu: 100m, memory: 256Mi }
    limits: { cpu: 1000m, memory: 1Gi }
