name: stale

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues 💀
        uses: actions/stale@v11
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 7
          days-before-pr-stale: -1
          days-before-pr-close: -1
          stale-issue-label: ":skull: stale"
          exempt-issue-labels: ":pushpin: pinned,:package: dependencies"
          exempt-all-milestones: true
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          close-issue-message: ""
